insert into Product (name, description, count, price, vid) values ('Smartphone Tripod', 'Adjustable tripod for smartphones and cameras.', 46, 29.99, 5);
insert into Product (name, description, count, price, vid) values ('Bock Beer Mustard', 'Flavorful mustard with a tangy kick, perfect for hot dogs and sandwiches.', 81, 2.29, 15);
insert into Product (name, description, count, price, vid) values ('Winter Insulated Jacket', 'Warm and stylish jacket for cold weather.', 55, 89.99, 21);
insert into Product (name, description, count, price, vid) values ('Fitness Resistance Bands', 'Set of resistance bands for home workouts.', 38, 29.99, 34);
insert into Product (name, description, count, price, vid) values ('Mini Waffle Maker', 'Compact waffle maker for perfect small waffles.', 51, 24.99, 1);
insert into Product (name, description, count, price, vid) values ('Graphic Tee', 'Soft cotton graphic tee available in various designs.', 58, 19.99, 9);
insert into Product (name, description, count, price, vid) values ('Foam Roller for Muscle Recovery', 'Use this foam roller for effective post-workout recovery.', 33, 29.99, 25);
insert into Product (name, description, count, price, vid) values ('Vegan Mayonnaise', 'Plant-based mayonnaise for a creamy taste.', 83, 4.49, 2);
insert into Product (name, description, count, price, vid) values ('Blackberry Compote', 'Sweet blackberry compote, perfect for topping desserts.', 38, 5.29, 39);
insert into Product (name, description, count, price, vid) values ('Foldable Electric Scooter', 'Compact electric scooter for commuting and short trips.', 96, 349.99, 4);
insert into Product (name, description, count, price, vid) values ('Peanut Butter Banana Smoothie', 'Smooth and creamy smoothie made with peanut butter and banana.', 99, 3.99, 8);
insert into Product (name, description, count, price, vid) values ('Blackberry Compote', 'Sweet blackberry compote, perfect for topping desserts.', 65, 5.29, 35);
insert into Product (name, description, count, price, vid) values ('Lentil Pasta', 'Gluten-free pasta made from lentils, high in protein.', 61, 4.99, 22);
insert into Product (name, description, count, price, vid) values ('Bluetooth Tracker', 'Smart tracker to locate keys or other items via app.', 26, 19.99, 27);
insert into Product (name, description, count, price, vid) values ('Stuffed Bell Peppers', 'Bell peppers stuffed with rice and vegetables', 25, 5.99, 27);
insert into Product (name, description, count, price, vid) values ('Caramelized Onion Dip Mix', 'A mix to create a delicious onion dip for parties or snacking.', 83, 2.29, 2);
insert into Product (name, description, count, price, vid) values ('Canvas Tote Bag', 'Durable canvas tote bag, perfect for everyday use.', 21, 19.99, 1);
insert into Product (name, description, count, price, vid) values ('Rechargeable Laptop Battery Pack', 'Portable battery pack to charge laptops while on the move.', 90, 49.99, 27);
insert into Product (name, description, count, price, vid) values ('Dog Collar', 'Adjustable dog collar with personalized tags.', 40, 15.99, 16);
insert into Product (name, description, count, price, vid) values ('Outdoor Camping Hammock', 'Lightweight and durable hammock for relaxing in nature.', 98, 29.99, 31);
insert into Product (name, description, count, price, vid) values ('Chocolate Covered Pretzels', 'Crunchy pretzels coated in rich chocolate, a sweet treat.', 89, 3.29, 33);
insert into Product (name, description, count, price, vid) values ('Almond Butter Cups', 'Rich chocolate cups filled with almond butter, a delicious treat.', 61, 3.29, 22);
insert into Product (name, description, count, price, vid) values ('Tennis Racket', 'Lightweight tennis racket for beginners and advanced players.', 91, 89.99, 19);
insert into Product (name, description, count, price, vid) values ('Teriyaki Chicken Stir-Fry', 'Frozen stir-fry mix with chicken, veggies, and teriyaki sauce.', 23, 6.99, 10);
insert into Product (name, description, count, price, vid) values ('Handmade Wooden Utensil Set', 'Unique handcrafted utensils for cooking and serving.', 75, 24.99, 23);
insert into Product (name, description, count, price, vid) values ('Quinoa', 'Protein-rich quinoa, a great alternative to rice.', 51, 4.49, 6);
insert into Product (name, description, count, price, vid) values ('Vegetable Fried Rice Mix', 'A quick and easy fried rice mix with colorful veggies and savory seasoning.', 42, 3.99, 36);
insert into Product (name, description, count, price, vid) values ('Matcha Green Tea Powder', 'High-quality matcha for making traditional tea or lattes.', 87, 14.99, 24);
insert into Product (name, description, count, price, vid) values ('Outdoor Adventure Kit', 'Complete outdoor kit for camping and hiking.', 63, 89.99, 7);
insert into Product (name, description, count, price, vid) values ('Vanilla Ice Cream', 'Creamy and rich vanilla ice cream, a classic dessert.', 38, 4.99, 20);
insert into Product (name, description, count, price, vid) values ('Smart Water Bottle with Hydration Reminder', 'Bottle that tracks your water intake and reminds you to drink.', 22, 39.99, 14);
insert into Product (name, description, count, price, vid) values ('Caramel Sauce', 'Rich sauce for desserts and ice cream.', 77, 3.49, 35);
insert into Product (name, description, count, price, vid) values ('Spicy Thai Chili Sauce', 'A sweet and spicy sauce for dipping or cooking.', 47, 3.29, 40);
insert into Product (name, description, count, price, vid) values ('Instant Read Meat Thermometer', 'Fast and accurate thermometer for grilling and cooking.', 96, 24.99, 38);
insert into Product (name, description, count, price, vid) values ('Portable Hammock', 'Lightweight hammock for easy setup anywhere.', 26, 27.99, 13);
insert into Product (name, description, count, price, vid) values ('Foot Massager Machine', 'Electric foot massager for relaxation and relief.', 81, 59.99, 3);
insert into Product (name, description, count, price, vid) values ('Cacao Powder', 'Unsweetened cacao powder for baking and smoothies.', 97, 4.49, 6);
insert into Product (name, description, count, price, vid) values ('Lightweight Rain Jacket', 'Water-resistant jacket ideal for outdoor activities, featuring a packable design.', 90, 79.99, 27);
insert into Product (name, description, count, price, vid) values ('Eco-Friendly Disposable Plates', 'Compostable plates suitable for various occasions.', 36, 22.99, 26);
insert into Product (name, description, count, price, vid) values ('Frozen Salmon Filets', 'Wild-caught salmon filets, perfect for grilling or baking.', 69, 12.99, 6);
insert into Product (name, description, count, price, vid) values ('Multifunctional Baby Bottle Warmer', 'Warmer for heating baby bottles and food jars.', 92, 39.99, 32);
insert into Product (name, description, count, price, vid) values ('Foam Muscle Roller', 'Relieve muscle tension and soreness with this foam roller.', 88, 24.99, 2);
insert into Product (name, description, count, price, vid) values ('Garlic and Herb Cream Cheese', 'Spreadable cream cheese with garlic and herbs.', 48, 3.49, 18);
insert into Product (name, description, count, price, vid) values ('Arcade Game Machine', 'Retro arcade machine for classic gaming.', 28, 299.99, 39);
insert into Product (name, description, count, price, vid) values ('Savory Mushroom Risotto', 'Creamy risotto infused with wild mushrooms.', 90, 6.49, 23);
insert into Product (name, description, count, price, vid) values ('Coffee Maker', 'Single-serve coffee maker with a built-in grinder.', 62, 89.99, 1);
insert into Product (name, description, count, price, vid) values ('Fitness Activity Journal', 'Journal to record workouts and nutrition.', 38, 14.99, 32);
insert into Product (name, description, count, price, vid) values ('Hiking Water Bottle with Filter', '8oz water bottle with built-in filter for clean drinking water.', 48, 29.99, 18);
insert into Product (name, description, count, price, vid) values ('Creamy Coleslaw Mix', 'Shredded cabbage and carrots for coleslaw.', 65, 2.39, 32);
insert into Product (name, description, count, price, vid) values ('Cranberry Citrus Sauce', 'A tangy sauce made with cranberries and citrus zest, perfect for turkey and chicken dishes.', 56, 3.99, 29);
insert into Product (name, description, count, price, vid) values ('Chewy Granola Bars', 'Oats and honey bars with a chewy texture and nutty flavor.', 60, 3.49, 12);
insert into Product (name, description, count, price, vid) values ('Collapsible Storage Crates', 'Space-saving crates for easy organization at home or while traveling.', 91, 18.99, 23);
insert into Product (name, description, count, price, vid) values ('Suede Ankle Booties', 'Chic suede ankle booties, perfect for dressing up or down.', 51, 79.99, 9);
insert into Product (name, description, count, price, vid) values ('Smashed Avocado with Lime', 'A creamy blend of avocados and lime juice, great for spreads or dips.', 65, 2.49, 7);
insert into Product (name, description, count, price, vid) values ('Travel Beach Blanket', 'Sand-resistant and compact for outdoor and beach use.', 66, 29.99, 24);
insert into Product (name, description, count, price, vid) values ('Sliced Cheese', 'Assorted sliced cheese, perfect for sandwiches.', 33, 4.49, 33);
insert into Product (name, description, count, price, vid) values ('Lentil Vegetable Stew', 'Hearty stew made with lentils and mixed vegetables, vegan-friendly.', 50, 4.49, 25);
insert into Product (name, description, count, price, vid) values ('Gaming Headset', 'Comfortable gaming headset with surround sound.', 66, 69.99, 28);
insert into Product (name, description, count, price, vid) values ('Voice-Controlled Speaker', 'Smart speaker with Alexa and music streaming features.', 66, 99.99, 18);
insert into Product (name, description, count, price, vid) values ('Herbal Tea Set', 'Assorted herbal tea bags for relaxation and wellness.', 46, 19.99, 19);
insert into Product (name, description, count, price, vid) values ('Wire Shelving Unit', 'Adjustable shelving unit for home or garage storage.', 69, 69.99, 39);
insert into Product (name, description, count, price, vid) values ('Chocolate Chip Cookie Dough', 'Ready-to-bake cookie dough packed with chocolate chips.', 37, 5.49, 18);
insert into Product (name, description, count, price, vid) values ('Comfortable Jogger Pants', 'Relaxed fit joggers made from soft fleece, ideal for lounging or workouts.', 38, 29.99, 12);
insert into Product (name, description, count, price, vid) values ('Wireless Earbuds', 'True wireless earbuds with touch control.', 41, 69.99, 39);
insert into Product (name, description, count, price, vid) values ('Black Bean Spaghetti', 'High-protein pasta made from black beans, gluten-free.', 21, 3.99, 16);
insert into Product (name, description, count, price, vid) values ('Mini Electric Kettle', 'Quick boiling kettle for small kitchens and dorms.', 41, 29.99, 20);
insert into Product (name, description, count, price, vid) values ('Buttermilk Pancakes', 'Fluffy pancakes with buttermilk flavor.', 74, 3.99, 39);
insert into Product (name, description, count, price, vid) values ('Customizable Name Puzzle', 'Personalized wooden puzzles for children that encourage learning.', 51, 29.99, 37);
insert into Product (name, description, count, price, vid) values ('Kids'' Trampoline', 'Safe and fun trampoline for children.', 56, 139.99, 18);
insert into Product (name, description, count, price, vid) values ('Pasta Sauce Mix', 'Just add water for a quick pasta sauce.', 93, 1.29, 39);
insert into Product (name, description, count, price, vid) values ('Pesto Pasta Salad', 'Cold pasta salad tossed with pesto and fresh vegetables.', 68, 4.99, 9);
insert into Product (name, description, count, price, vid) values ('Vegan Taco Seasoning', 'Spice blend for creating flavorful vegan taco filling.', 38, 2.49, 29);
insert into Product (name, description, count, price, vid) values ('Stainless Steel Water Pitcher', 'Insulated pitcher to keep beverages cold or hot.', 57, 39.99, 19);
insert into Product (name, description, count, price, vid) values ('Tattoo Kit', 'Complete tattoo kit for beginners and professionals.', 96, 99.99, 12);
insert into Product (name, description, count, price, vid) values ('Lemon Herb Grilled Chicken', 'Tender grilled chicken marinated in lemon herbs.', 31, 9.99, 17);
insert into Product (name, description, count, price, vid) values ('Pine Nuts', 'Nutty flavor perfect for pesto and salads.', 61, 7.99, 14);
insert into Product (name, description, count, price, vid) values ('Magnetic Whiteboard', 'Reusable whiteboard for notes and reminders with magnetic backing.', 64, 34.99, 14);
insert into Product (name, description, count, price, vid) values ('Almond Flour Cookies', 'Delicious cookies made with almond flour for a gluten-free treat.', 34, 4.99, 5);
insert into Product (name, description, count, price, vid) values ('Stainless Steel Straws', 'Set of reusable stainless steel straws for drinks.', 90, 12.99, 19);
insert into Product (name, description, count, price, vid) values ('Peach Preserves', 'Sweet and fruity peach preserves, perfect for spreading on toast.', 26, 3.79, 9);
insert into Product (name, description, count, price, vid) values ('Lentil Vegetable Stew', 'Hearty stew made with lentils and mixed vegetables, vegan-friendly.', 54, 4.49, 11);
insert into Product (name, description, count, price, vid) values ('Organic Spinach', 'Fresh organic spinach, great for salads or cooking.', 37, 2.99, 8);
insert into Product (name, description, count, price, vid) values ('Luxury Bath Salts', 'Scented bath salts for relaxation and self-care.', 89, 19.99, 13);
insert into Product (name, description, count, price, vid) values ('Indian Curry Sauce', 'Authentic Indian curry sauce for quick meals.', 72, 3.69, 11);
insert into Product (name, description, count, price, vid) values ('Casual Long Cardigan', 'A cozy long cardigan designed for layering in any season.', 89, 45.99, 4);
insert into Product (name, description, count, price, vid) values ('Vanilla Bean Greek Yogurt', 'Smooth Greek yogurt infused with vanilla bean flavor.', 79, 1.99, 39);
insert into Product (name, description, count, price, vid) values ('Canned Sardines', 'Savory sardines packed in olive oil.', 32, 3.29, 4);
insert into Product (name, description, count, price, vid) values ('Insulated Cooler', 'Leak-proof cooler bag ideal for picnics and camping.', 62, 39.99, 17);
insert into Product (name, description, count, price, vid) values ('Chili Lime Corn Chips', 'Crunchy corn chips flavored with chili and lime for a zesty kick.', 73, 2.79, 21);
insert into Product (name, description, count, price, vid) values ('Kettle BBQ Grill', 'Charcoal kettle grill perfect for backyard barbecues.', 32, 99.99, 30);
insert into Product (name, description, count, price, vid) values ('Pet Water Fountain', 'Automatic water fountain for pets with filtration.', 84, 39.99, 1);
insert into Product (name, description, count, price, vid) values ('Wooden Children''s Play Kitchen', 'Interactive kitchen set for imaginative play.', 25, 129.99, 3);
insert into Product (name, description, count, price, vid) values ('Decorative LED Neon Sign', 'Bright, vibrant sign to add flair to any space.', 92, 45.99, 35);
insert into Product (name, description, count, price, vid) values ('Thai Green Curry Paste', 'A rich curry paste for making authentic Thai green curry at home.', 29, 2.49, 30);
insert into Product (name, description, count, price, vid) values ('Pet Camera with Treat Dispenser', 'Monitor and interact with your pet remotely with this camera.', 46, 149.99, 22);
insert into Product (name, description, count, price, vid) values ('Personal Blender with Travel Cup', 'Blender for smoothies with a portable cup.', 97, 39.99, 38);
insert into Product (name, description, count, price, vid) values ('Digital Bullet Journal', 'Stylish digital journaling app for notes and organizing tasks.', 96, 24.99, 14);
insert into Product (name, description, count, price, vid) values ('Raspberry Lemonade Mix', 'A refreshing drink mix that combines sweet raspberries and tart lemons, perfect for summer.', 83, 3.99, 18);
insert into Product (name, description, count, price, vid) values ('Fitness Jump Box', 'Durable and adjustable jump box for effective workouts.', 42, 69.99, 4);
insert into Product (name, description, count, price, vid) values ('High-Quality Yoga Block', 'Foam yoga block for enhancing poses and stability.', 66, 12.99, 1);
insert into Product (name, description, count, price, vid) values ('Honey Roasted Peanuts', 'Crunchy peanuts coated in honey, perfect for snacking.', 95, 3.19, 12);
insert into Product (name, description, count, price, vid) values ('Noise-Canceling Headphones', 'High-quality headphones that block out external noise for immersive listening.', 62, 119.99, 31);
insert into Product (name, description, count, price, vid) values ('Smart Scale', 'Wi-Fi smart scale for tracking weight and BMI.', 48, 59.99, 33);
insert into Product (name, description, count, price, vid) values ('Coconut Rice', 'Fluffy rice cooked with coconut milk for a tropical twist.', 72, 2.29, 12);
insert into Product (name, description, count, price, vid) values ('Electric Toothbrush Holder', 'Sanitary holder that ensures your toothbrush stays clean.', 51, 14.99, 17);
insert into Product (name, description, count, price, vid) values ('Cheesy Cauliflower Bake', 'A frozen cheesy bake made with cauliflower, great as a side dish or a vegetarian meal.', 50, 5.49, 32);
insert into Product (name, description, count, price, vid) values ('Spinach and Feta Wraps', 'Whole wheat wraps filled with spinach and feta cheese.', 49, 4.99, 34);
insert into Product (name, description, count, price, vid) values ('Casual Long Cardigan', 'A cozy long cardigan designed for layering in any season.', 68, 45.99, 8);
insert into Product (name, description, count, price, vid) values ('Teriyaki Sauce', 'Sweet and savory sauce for marinating and glazing meats or vegetables.', 72, 2.99, 21);
insert into Product (name, description, count, price, vid) values ('Blueberry Chia Jam', 'Homemade jam made with blueberries and chia seeds, no added sugar.', 53, 4.99, 22);
insert into Product (name, description, count, price, vid) values ('Nutritional Yeast', 'A healthy vegan cheese alternative packed with nutrients and flavor.', 94, 3.59, 15);
insert into Product (name, description, count, price, vid) values ('Lemon Garlic Shrimp', 'Marinated shrimp in a garlic and lemon sauce, perfect for grilling.', 99, 8.99, 37);
insert into Product (name, description, count, price, vid) values ('Basic V-Neck T-Shirt', 'A staple v-neck t-shirt that pairs well with anything.', 97, 19.99, 28);
insert into Product (name, description, count, price, vid) values ('Handcrafted Wooden Coasters', 'Set of unique wooden coasters for drinks and decor.', 55, 19.99, 2);
insert into Product (name, description, count, price, vid) values ('Adjustable Standing Desk', 'Ergonomic desk that adjusts height for standing or sitting.', 82, 299.99, 24);
insert into Product (name, description, count, price, vid) values ('Cream Cheese', 'Smooth and creamy, ideal for spreads or baking.', 48, 2.69, 6);
insert into Product (name, description, count, price, vid) values ('Cotton Tote Bag Set', 'Reusable tote bags for shopping and eco-friendly living.', 54, 29.99, 35);
insert into Product (name, description, count, price, vid) values ('Cotton Quilted Throw Blanket', 'Cozy throw blanket perfect for adding warmth to your home.', 83, 39.99, 25);
insert into Product (name, description, count, price, vid) values ('Lentil Vegetable Curry', 'A flavorful lentil curry cooked with vegetables and spices.', 27, 4.49, 4);
insert into Product (name, description, count, price, vid) values ('Pepperoni Pizza Roll-Ups', 'Savory pizza filled with pepperoni and cheese, ready to microwave.', 48, 5.99, 27);
insert into Product (name, description, count, price, vid) values ('Eco-Friendly Notepad', 'Notepad made from recycled paper for sustainable note-taking.', 82, 8.99, 27);
insert into Product (name, description, count, price, vid) values ('Luminous Night Light', 'Soft glow night light for children''s rooms or bedside.', 58, 15.99, 11);
insert into Product (name, description, count, price, vid) values ('Banana Chips', 'Crunchy and sweet banana chips, a great on-the-go snack.', 76, 1.99, 2);
insert into Product (name, description, count, price, vid) values ('Honey mustard chicken tenders', 'Golden crispy chicken tenders coated with honey mustard flavor.', 69, 7.99, 40);
insert into Product (name, description, count, price, vid) values ('Coconut Lime Rice', 'Flavorful rice mixed with coconut and lime, a tropical side dish.', 99, 2.99, 6);
insert into Product (name, description, count, price, vid) values ('Cheese Stuffed Jalapenos', 'Spicy jalapenos stuffed with cheese, ideal for appetizers.', 21, 5.99, 9);
insert into Product (name, description, count, price, vid) values ('Chocolate Covered Pretzels', 'Crunchy pretzels coated in rich chocolate, a sweet treat.', 31, 3.29, 27);
insert into Product (name, description, count, price, vid) values ('Coconut Oil Spray', 'A zero-calorie coconut oil spray for cooking and baking.', 59, 4.99, 23);
insert into Product (name, description, count, price, vid) values ('Tuscan Bean Soup', 'A hearty mix of beans in a flavorful tomato broth.', 30, 2.49, 32);
insert into Product (name, description, count, price, vid) values ('Handmade Leather Wallet', 'High-quality leather wallet with multiple compartments.', 41, 49.99, 20);
insert into Product (name, description, count, price, vid) values ('Rice Cakes', 'Light and crispy rice cakes, a perfect low-calorie snack.', 23, 2.29, 14);
insert into Product (name, description, count, price, vid) values ('Folding Exercise Bike', 'Space-saving bike for indoor workouts.', 77, 199.99, 21);
insert into Product (name, description, count, price, vid) values ('Car Phone Mount', 'Adjustable phone mount for car dashboard.', 51, 15.99, 22);
insert into Product (name, description, count, price, vid) values ('Acoustic Guitar', 'Beginner-friendly acoustic guitar with natural finish.', 42, 199.99, 20);
insert into Product (name, description, count, price, vid) values ('Window Bird Feeder with Suction Cups', 'Clear feeder that attaches to windows for bird watching.', 56, 28.99, 22);
insert into Product (name, description, count, price, vid) values ('Gingerbread House Kit', 'Everything you need to build a festive gingerbread house.', 86, 6.99, 1);
insert into Product (name, description, count, price, vid) values ('Crispy Chickpeas', 'Roasted chickpeas seasoned for a crunchy snack.', 60, 2.99, 7);
insert into Product (name, description, count, price, vid) values ('Toilet Paper (12 rolls)', 'Soft and strong toilet paper for everyday use.', 33, 8.99, 13);
insert into Product (name, description, count, price, vid) values ('Caramel Sauce', 'Rich sauce for desserts and ice cream.', 87, 3.49, 2);
insert into Product (name, description, count, price, vid) values ('Indestructible Dog Toy', 'Durable toy designed for heavy chewers.', 51, 15.99, 16);
insert into Product (name, description, count, price, vid) values ('Kids'' Science Experiment Kit', 'Engaging kit with science experiments for children.', 50, 29.99, 7);
insert into Product (name, description, count, price, vid) values ('Portable Bluetooth Keyboard', 'Compact keyboard for tablets and smartphones.', 75, 39.99, 35);
insert into Product (name, description, count, price, vid) values ('Cranberry Lime Sparkling Water', 'Refreshing sparkling water infused with cranberry and lime flavors.', 80, 1.5, 30);
insert into Product (name, description, count, price, vid) values ('Chicken Sausage', 'Flavorful chicken sausage, low in fat and fully cooked.', 95, 6.99, 18);
insert into Product (name, description, count, price, vid) values ('Weighted Blanket', 'Therapeutic weighted blanket for better sleep.', 49, 79.99, 29);
insert into Product (name, description, count, price, vid) values ('Corn Tortillas', 'Soft and warm corn tortillas, perfect for tacos and burritos.', 26, 2.49, 9);
insert into Product (name, description, count, price, vid) values ('Raspberry Vanilla Greek Yogurt', 'Creamy Greek yogurt infused with raspberry and vanilla flavors.', 38, 3.49, 19);
insert into Product (name, description, count, price, vid) values ('Chocolate Raspberry Tart', 'Rich tart filled with chocolate and raspberry, a gourmet dessert.', 55, 9.99, 1);
insert into Product (name, description, count, price, vid) values ('Garlic and Herb Rub', 'A seasoning blend of garlic and herbs to enhance any dish.', 33, 2.29, 8);
insert into Product (name, description, count, price, vid) values ('Elegant Maxi Skirt', 'Float through the day in this beautiful floor-length skirt.', 98, 44.99, 12);
insert into Product (name, description, count, price, vid) values ('Adjustable Pet Feeder', 'Convenient feeder that adjusts to your pet''s height.', 64, 39.99, 21);
insert into Product (name, description, count, price, vid) values ('Lentil Pasta', 'Gluten-free pasta made from lentils, high in protein.', 72, 4.99, 18);
insert into Product (name, description, count, price, vid) values ('Watercolor Brush Pens', 'Set of brush pens for colorful and creative painting.', 25, 19.99, 37);
insert into Product (name, description, count, price, vid) values ('Coconut Cream Pie', 'Delicious pie filled with coconut cream and topped with whipped cream.', 69, 9.49, 3);
insert into Product (name, description, count, price, vid) values ('Cinnamon Sugar Tortilla Chips', 'Crispy chips with a sweet twist, perfect for dipping.', 57, 3.29, 1);
insert into Product (name, description, count, price, vid) values ('Adjustable Laptop Desk', 'Portable desk that can be adjusted for sitting or standing.', 95, 59.99, 24);
insert into Product (name, description, count, price, vid) values ('Smart LED Desk Lamp', 'Adjustable lamp with multiple brightness levels and colors.', 85, 39.99, 35);
insert into Product (name, description, count, price, vid) values ('Floral Summer Dress', 'Light and breezy dress perfect for summer outings with a vibrant floral pattern.', 79, 39.99, 36);
insert into Product (name, description, count, price, vid) values ('Marinara Sauce', 'Classic marinara sauce for all pasta dishes.', 60, 3.49, 30);
insert into Product (name, description, count, price, vid) values ('Almond Milk Yogurt', 'Creamy yogurt made from almond milk, vegan-friendly.', 69, 1.99, 10);
insert into Product (name, description, count, price, vid) values ('Raspberry Lemonade Mix', 'A refreshing drink mix that combines sweet raspberries and tart lemons, perfect for summer.', 64, 3.99, 35);
insert into Product (name, description, count, price, vid) values ('Ready-to-Eat Chili', 'Spicy chili in a can, ready to eat for a filling meal.', 27, 2.99, 39);
insert into Product (name, description, count, price, vid) values ('Tomato Paste', 'Concentrated tomato paste, great for sauces.', 21, 1.29, 25);
insert into Product (name, description, count, price, vid) values ('Sweet Chili Sauce', 'A sweet and spicy sauce, great for dipping or cooking.', 88, 2.99, 36);
insert into Product (name, description, count, price, vid) values ('Chocolate Peanut Butter Cups', 'Delicious dark chocolate cups filled with creamy peanut butter.', 35, 2.29, 40);
insert into Product (name, description, count, price, vid) values ('Portable Pet Bathing Tool', 'Handheld sprayer designed for washing pets easily.', 60, 29.99, 25);
insert into Product (name, description, count, price, vid) values ('Slim Wallet', 'RFID-blocking slim wallet for cards and cash.', 29, 24.99, 24);
insert into Product (name, description, count, price, vid) values ('Oatmeal Raisin Cookies', 'Delicious cookies packed with oats and raisins.', 83, 3.49, 40);
insert into Product (name, description, count, price, vid) values ('Buffalo Chicken Dip', 'Spicy and creamy dip made with shredded chicken, perfect for parties.', 100, 5.99, 13);
insert into Product (name, description, count, price, vid) values ('Sushi Roll Kit', 'All ingredients needed to make your own sushi', 73, 9.99, 23);
insert into Product (name, description, count, price, vid) values ('Wireless Security System', 'Comprehensive camera and alert system for home security.', 64, 299.99, 16);
insert into Product (name, description, count, price, vid) values ('Peach Slices in Syrup', 'Sweet and tender peach slices preserved in syrup, great for desserts.', 99, 2.59, 12);
insert into Product (name, description, count, price, vid) values ('Laptop Sleeve', 'Padded laptop sleeve for protection against scratches.', 21, 24.99, 2);
insert into Product (name, description, count, price, vid) values ('Peanut Butter Chocolate Chip Bars', 'Chewy bars made with peanut butter and chocolate chips.', 91, 4.59, 38);
insert into Product (name, description, count, price, vid) values ('Vegan Chickpea Salad', 'Healthy salad made with chickpeas, vegetables, and a lemon dressing.', 55, 3.99, 31);
insert into Product (name, description, count, price, vid) values ('Cable Knit Cardigan', 'Cozy cable knit cardigan to layer during chilly evenings.', 62, 49.99, 25);
insert into Product (name, description, count, price, vid) values ('Portable Water Filter', 'Lightweight water filter for outdoor adventures.', 86, 29.99, 22);
insert into Product (name, description, count, price, vid) values ('Camping Tent', 'Spacious 2-person camping tent with waterproof cover.', 85, 79.99, 4);
insert into Product (name, description, count, price, vid) values ('Cat Tree', 'Multi-level cat tree for climbing and scratching.', 100, 99.99, 38);
insert into Product (name, description, count, price, vid) values ('Sushi Rice', 'Short-grain sushi rice for perfect rolls.', 81, 3.99, 5);
